# Generated by Django 3.2.4 on 2021-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_ip_addr_device_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='get_community',
            field=models.CharField(default='public', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='set_community',
            field=models.CharField(default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_port',
            field=models.IntegerField(default=161),
        ),
    ]
