FROM postgres:12.2
COPY init.sql /docker-entrypoint-initdb.d/

# COPY data/postgresql.conf /var/lib/postgresql/data_config/postgresql.conf
# COPY data/pg_hba.conf /var/lib/postgresql/data_config/pg_hba.conf
