# Generated by Django 3.2 on 2021-04-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
